# Generated by Django 5.1.6 on 2025-02-27 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "perfil", "verbose_name_plural": "perfiles"},
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="¿Desde cuando lo sigue?"
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_set",
                        to="profiles.userprofile",
                        verbose_name="¿Quien sigue?",
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_set",
                        to="profiles.userprofile",
                        verbose_name="¿A quein sigue?",
                    ),
                ),
            ],
            options={
                "verbose_name": "seguidor",
                "verbose_name_plural": "seguidores",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="followers",
            field=models.ManyToManyField(
                related_name="following",
                through="profiles.Follow",
                to="profiles.userprofile",
            ),
        ),
    ]
