# Generated by Django 5.1.6 on 2025-02-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_caption_alter_post_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.AddField(
            model_name="post",
            name="imagen",
            field=models.ImageField(
                default="", upload_to="posts_images/", verbose_name="imagen"
            ),
            preserve_default=False,
        ),
    ]
